services:
  db:
    image: postgres:16-alpine
    container_name: betterhr-db
    environment:
      POSTGRES_DB: betterhr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - betterhr-net

  localstack:
    image: localstack/localstack:latest
    container_name: betterhr-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3,cognito-idp
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack_init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - betterhr-net

networks:
  betterhr-net:
    name: betterhr-net
    driver: bridge

volumes:
  postgres_data:
